using System.Collections;
using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

public class PathCreator : MonoBehaviour
{
    LineRenderer lineRenderer;

    List<Vector3> points = new List<Vector3>();

    public Action<IEnumerable<Vector3>> OnNewPathCreated = delegate { };

    void Awake()
    {
        lineRenderer = GetComponent<LineRenderer>();
    }

    void Update()
    {
        if (Input.GetMouseButtonDown(0))
            points.Clear();

        if (Input.GetMouseButton(0)) 
        {
            Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            RaycastHit hitInfo;

            if (Physics.Raycast(ray,out hitInfo))
            {
                if (DistanceToLastPoint(hitInfo.point) > 1f)
                {
                    points.Add(hitInfo.point);

                    lineRenderer.positionCount = points.Count;
                    lineRenderer.SetPositions(points.ToArray());

                }
            }
        }
        else if (Input.GetMouseButtonUp(0))
        {
            OnNewPathCreated(points);
        }

        float DistanceToLastPoint(Vector3 point) 
        {
            if (!points.Any())
                return Mathf.Infinity;
            return Vector3.Distance(points.Last(), point);





        }


    }
}
